// Copyright (c) Richasy. All rights reserved.
// Licensed under the MIT License.

namespace Richasy.MpvKernel.Core.Enums;

/// <summary>
/// Auto create playlist kind.
/// </summary>
public enum AutoCreatePlaylistKind
{
    /// <summary>
    /// Load a single file (default).
    /// </summary>
    No,

    /// <summary>
    /// Create a playlist from the parent directory with files matching --directory-filter-types.
    /// </summary>
    Filter,

    /// <summary>
    /// Create a playlist from the parent directory with files matching the same category as the currently loaded file. One of the *-exts is selected based on the input file and only files with matching extensions are added to the playlist. If the input file itself is not matched to any extension list, the playlist is not autogenerated.
    /// </summary>
    Same
}
