<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.22621.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
	<AssemblyName>Richasy.MpvKernel.WinUI</AssemblyName>
	<RootNamespace>$(AssemblyName)</RootNamespace>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	<IsAotCompatible>true</IsAotCompatible>
	<EnableMsixTooling>true</EnableMsixTooling>
	<EnablePriGenTooling>true</EnablePriGenTooling>
	<WebView2EnableCsWinRTProjectionExcludeCoreRef>true</WebView2EnableCsWinRTProjectionExcludeCoreRef>
  </PropertyGroup>

  <Import Project="$(RepoRoot)/src/nuget-package.props" />
  
  <PropertyGroup>
  	<!-- NuGet Package Settings -->
  	<Title>Mpv Kernel - WinUI</Title>
  	<Description>适用于 WinUI 的播放窗口及控件接口.</Description>
  </PropertyGroup>

  <ItemGroup>
  	<None Include="bin/$(Configuration)/$(TargetFramework)/$(AssemblyName).pri" Pack="true" PackagePath="lib/$(TargetFramework.TrimEnd('.0'))/" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="PlayerInteractivePanel.xaml" />
    <None Remove="Themes\Generic.xaml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" />
    <PackageReference Include="Microsoft.WindowsAppSDK" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MpvKernel.Core\MpvKernel.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Page Update="PlayerInteractivePanel.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Themes\Generic.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Controls\PlayerInteractivePanel\" />
  </ItemGroup>
  
</Project>